#!/usr/bin/env node
// Assembles each skills/<name>/SKILL.md from shared/git-flow/, so a skill folder is self-contained
// and portable across Claude Code / Codex / OpenCode. Also checks the manifests agree with disk.
//
//   npm run build    build
//   npm run check    verify committed SKILL.md files are current and manifests consistent (exit 1)
//
// Add a skill: a head in shared/<set>/heads/<name>.md, an entry in SKILLS below. The stage bodies
// are shared, so nothing is copied by hand.
//
// The stages are inlined rather than shipped as references/ that every SKILL.md then tells the
// agent to read. Those reads were unconditional — 2 to 5 extra tool calls before any work, buying
// nothing that loading the body up front doesn't.

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync, rmSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// One file per stage, so a skill carries only the stages it runs. `commit` gets preflight, the
// commit stage and the report — nothing about pushing or pull requests.
const STAGES = {
  core: "shared/git-flow/core.md",
  remote: "shared/git-flow/remote.md",
  guardrails: "shared/git-flow/guardrails.md",
  branch: "shared/git-flow/branch.md",
  commit: "shared/git-flow/commit.md",
  push: "shared/git-flow/push.md",
  pr: "shared/git-flow/pr.md",
  "sync-base": "shared/git-flow/sync-base.md",
  report: "shared/git-flow/report.md",
};

const HEADS = "shared/git-flow/heads";

// Membership here IS the stage list each SKILL.md claims in its opening line — keep the two in step.
const SKILLS = [
  { name: "branch-commit-push-pr", stages: ["core", "remote", "guardrails", "branch", "commit", "push", "pr", "report"] },
  { name: "branch-commit-push", stages: ["core", "remote", "guardrails", "branch", "commit", "push", "report"] },
  { name: "branch-commit", stages: ["core", "remote", "guardrails", "branch", "commit", "report"] },
  { name: "commit-push-pr", stages: ["core", "remote", "guardrails", "commit", "push", "pr", "report"] },
  { name: "commit-push", stages: ["core", "remote", "guardrails", "commit", "push", "report"] },
  { name: "commit", stages: ["core", "guardrails", "commit", "report"] },
  { name: "push-pr", stages: ["core", "remote", "guardrails", "push", "pr", "report"] },
  { name: "branch", stages: ["core", "remote", "guardrails", "branch", "report"] },
  { name: "push", stages: ["core", "remote", "guardrails", "push", "report"] },
  { name: "pr", stages: ["core", "remote", "guardrails", "pr", "report"] },
  // Its own procedure and report block, so no shared report stage.
  { name: "sync-base", stages: ["core", "remote", "guardrails", "sync-base"] },
];

// A generated body has to stay readable in one pass. Loading it is the cost the references used to
// hide behind extra tool calls, so it is capped rather than left to grow.
const MAX_LINES = 400;

const BANNER =
  "<!-- generated by scripts/build.mjs from shared/git-flow/ — edit the source there, then run: npm run build -->";

const isFile = (path) => existsSync(path) && statSync(path).isFile();
const safeRelative = (path) => !isAbsolute(path) && !path.split(/[\\/]/).includes("..");

// Compare and write LF, whatever the working tree holds. `.gitattributes` pins *.md to eol=lf, but
// a checkout made under core.autocrlf=true before that yields CRLF sources — and a byte compare
// then calls every file stale forever, because the banner is LF while the body is CRLF and
// committing the mix normalises it straight back.
const norm = (s) => s.replace(/\r\n/g, "\n");

const check = process.argv.includes("--check");
let stale = 0;
let written = 0;

const setProblems = [];
const seen = new Set();
for (const [stage, source] of Object.entries(STAGES)) {
  if (!safeRelative(source) || !source.startsWith("shared/")) {
    setProblems.push(`stage ${stage} source must stay under shared/: ${source}`);
  }
  if (!isFile(join(ROOT, source))) setProblems.push(`missing stage source: ${source}`);
}
for (const skill of SKILLS) {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(skill.name)) {
    setProblems.push(`unsafe skill name: ${skill.name}`);
  }
  if (seen.has(skill.name)) setProblems.push(`${skill.name} is listed more than once`);
  seen.add(skill.name);
  if (!skill.stages.length) setProblems.push(`${skill.name} lists no stages`);
  if (skill.stages[0] !== "core") setProblems.push(`${skill.name} must start with the core stage`);
  const used = new Set();
  for (const stage of skill.stages) {
    if (!STAGES[stage]) setProblems.push(`${skill.name} names an unknown stage: ${stage}`);
    if (used.has(stage)) setProblems.push(`${skill.name} names ${stage} more than once`);
    used.add(stage);
  }
  const head = join(ROOT, HEADS, `${skill.name}.md`);
  if (!isFile(head)) setProblems.push(`missing head: ${HEADS}/${skill.name}.md`);
  if (!statSync(join(ROOT, "skills", skill.name), { throwIfNoEntry: false })?.isDirectory()) {
    setProblems.push(`missing folder: skills/${skill.name}/`);
  }
}
if (setProblems.length) {
  for (const problem of setProblems) console.error(`skills: ${problem}`);
  process.exit(1);
}

// The banner goes after the frontmatter, not before it: `name` and `description` are only read when
// the block starts on line 1.
function assemble(skill) {
  const head = norm(readFileSync(join(ROOT, HEADS, `${skill.name}.md`), "utf8")).trimEnd();
  const fm = /^(---\n[\s\S]*?\n---)\n?([\s\S]*)$/.exec(head);
  if (!fm) {
    console.error(`head ${HEADS}/${skill.name}.md has no --- frontmatter block`);
    process.exit(1);
  }
  const bodies = skill.stages.map((stage) =>
    norm(readFileSync(join(ROOT, STAGES[stage]), "utf8")).trim()
  );
  return `${fm[1]}\n\n${BANNER}\n\n${[fm[2].trim(), ...bodies].join("\n\n")}\n`;
}

for (const skill of SKILLS) {
  const outPath = join(ROOT, "skills", skill.name, "SKILL.md");
  const body = assemble(skill);
  const lines = body.split("\n").length - 1;
  if (lines > MAX_LINES) {
    console.error(
      `skills/${skill.name}/SKILL.md would be ${lines} lines, over the ${MAX_LINES}-line budget — trim a stage in shared/git-flow/`
    );
    process.exit(1);
  }
  const current = isFile(outPath) ? norm(readFileSync(outPath, "utf8")) : null;
  if (current === body) continue;
  if (check) {
    console.error(`stale: skills/${skill.name}/SKILL.md`);
    stale++;
    continue;
  }
  writeFileSync(outPath, body);
  console.log(`wrote skills/${skill.name}/SKILL.md (${lines} lines)`);
  written++;
}

// --- manifest + skill folder consistency ---------------------------------------------------
// The plugin install path ships exactly what plugin.json lists, so a skill missing from that
// array is invisible there even though `npx skills add` finds it. Names must also agree across
// plugin.json and the marketplace entry, or `/plugin install <name>@<marketplace>` won't resolve.
// The per-skill checks below cover the AGENTS.md invariants a reviewer can't see at a glance:
// frontmatter name == folder name, a description exists, no root SKILL.md, nothing pointing outside
// the folder, and no leftover references/ now that the stages are inlined.
const problems = [];

const skillFolders = readdirSync(join(ROOT, "skills"), { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();
const onDisk = skillFolders.filter((name) => isFile(join(ROOT, "skills", name, "SKILL.md")));
const built = new Set(SKILLS.map((s) => s.name));

const plugin = JSON.parse(readFileSync(join(ROOT, ".claude-plugin/plugin.json"), "utf8"));
const listed = (plugin.skills ?? []).map((p) => p.replace(/^\.\/skills\//, "")).sort();

// `npx skills add` searches shallowest-first, so a root SKILL.md shadows everything under skills/.
if (existsSync(join(ROOT, "SKILL.md"))) {
  problems.push("root SKILL.md exists — it shadows every skill under skills/ for `npx skills add`; delete it");
}

for (const name of skillFolders) {
  if (!isFile(join(ROOT, "skills", name, "SKILL.md"))) {
    problems.push(`skills/${name}/ has no regular SKILL.md file`);
  }
  if (!built.has(name)) {
    problems.push(`skills/${name}/ is not listed in SKILLS — its SKILL.md is hand-written and will drift`);
  }
}

// Enough of a YAML reader for the two keys every tool reads. Handles `key: value` and the
// `key: >` block scalar the descriptions use.
function frontmatter(text) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text);
  if (!match) return null;
  const out = {};
  let key = null;
  for (const line of match[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z][\w-]*):[ \t]*(.*)$/.exec(line);
    if (kv) {
      key = kv[1];
      const value = kv[2].trim();
      out[key] = /^[|>][-+]?$/.test(value) ? "" : value;
    } else if (key && /^[ \t]+\S/.test(line)) {
      out[key] = `${out[key]} ${line.trim()}`.trim();
    }
  }
  return out;
}

for (const name of onDisk) {
  const skillDir = join(ROOT, "skills", name);
  const text = readFileSync(join(skillDir, "SKILL.md"), "utf8");
  const fm = frontmatter(text);

  if (!fm) {
    problems.push(`skills/${name}/SKILL.md has no --- frontmatter block`);
  } else {
    // The ecosystem CLI keys off `name`, so a mismatch installs the folder under one name while
    // tools route on the other.
    if (fm.name !== name) {
      problems.push(`skills/${name}/SKILL.md frontmatter name "${fm.name ?? ""}" != folder name "${name}"`);
    }
    if (!fm.description) {
      problems.push(`skills/${name}/SKILL.md has no description — the only routing signal a tool sees`);
    }
  }

  if (/\$\{CLAUDE_PLUGIN_ROOT\}|(?:^|[\s(`'"])\.\.\//m.test(text) || /(?:^|[\s(`'"])[A-Za-z]:[\\/]/m.test(text) || /`\/(?:[^`\s]+\/[^`\s]+|[^/`\s]*\.[^`\s]+)`/.test(text)) {
    problems.push(`skills/${name}/SKILL.md references content outside its own folder`);
  }
  for (const link of text.matchAll(/\]\(([^)]+)\)/g)) {
    const target = link[1].split("#", 1)[0];
    if (target && !/^[a-z][a-z0-9+.-]*:/i.test(target)) {
      const local = resolve(skillDir, target);
      const within = relative(skillDir, local);
      if (within.startsWith("..") || isAbsolute(within)) {
        problems.push(`skills/${name}/SKILL.md link escapes the skill folder: ${target}`);
      }
    }
  }

  // The stages are inlined, so a references/ folder is a leftover and a SKILL.md citing one is a
  // dangling pointer that costs a tool call to discover.
  if (existsSync(join(skillDir, "references"))) {
    if (check) {
      problems.push(`skills/${name}/references/ still exists — the stages are inlined now; delete it`);
    } else {
      rmSync(join(skillDir, "references"), { recursive: true, force: true });
      console.log(`removed skills/${name}/references/`);
    }
  }
  if (/references\/[\w.-]+\.md/.test(text)) {
    problems.push(`skills/${name}/SKILL.md cites a references/ file — the stages are inlined; drop the citation`);
  }

  if (!listed.includes(name)) problems.push(`plugin.json "skills" is missing "./skills/${name}"`);
  const openaiPath = join(skillDir, "agents/openai.yaml");
  if (!isFile(openaiPath)) {
    problems.push(`skills/${name}/agents/openai.yaml missing (Codex display metadata)`);
  } else {
    const yaml = readFileSync(openaiPath, "utf8");
    const display = /^\s{2}display_name:\s*["']?(.+?)["']?\s*$/m.exec(yaml)?.[1]?.trim();
    const short = /^\s{2}short_description:\s*["']?(.+?)["']?\s*$/m.exec(yaml)?.[1]?.trim();
    const prompt = /^\s{2}default_prompt:\s*["']?(.+?)["']?\s*$/m.exec(yaml)?.[1]?.trim();
    if (!/^interface:\s*$/m.test(yaml) || !display || !short) {
      problems.push(`skills/${name}/agents/openai.yaml needs interface.display_name and interface.short_description`);
    }
    if (prompt && !prompt.includes(`$${name}`)) {
      problems.push(`skills/${name}/agents/openai.yaml default_prompt must reference $${name}`);
    }
    for (const match of yaml.matchAll(/^\s{2}icon_(?:small|large):\s*["']?(.+?)["']?\s*$/gm)) {
      const asset = match[1].trim();
      const assetPath = resolve(dirname(openaiPath), asset);
      const insideSkill = relative(skillDir, assetPath);
      if (!insideSkill || insideSkill.startsWith("..") || isAbsolute(insideSkill) || !isFile(assetPath)) {
        problems.push(`skills/${name}/agents/openai.yaml icon path is missing or escapes the skill: ${asset}`);
      }
    }
  }
}
for (const name of listed) {
  if (!onDisk.includes(name)) problems.push(`plugin.json lists "./skills/${name}", which has no SKILL.md`);
}

const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
if (pkg.version !== plugin.version) {
  problems.push(`package.json version "${pkg.version}" != plugin.json version "${plugin.version}"`);
}

const market = JSON.parse(readFileSync(join(ROOT, ".claude-plugin/marketplace.json"), "utf8"));
if (market.name !== plugin.name) {
  problems.push(`marketplace name "${market.name ?? ""}" != plugin.json name "${plugin.name}"`);
}
const entries = (market.plugins ?? []).filter((p) => p.source === "./");
const entry = entries[0];
if (entries.length !== 1) problems.push('marketplace.json must have exactly one plugin entry with "source": "./"');
else if (entry.name !== plugin.name) {
  problems.push(
    `marketplace plugin name "${entry.name}" != plugin.json name "${plugin.name}" — ` +
      `/plugin install would not resolve`
  );
}

for (const p of problems) console.error(`manifest: ${p}`);

if (check) {
  if (stale) console.error(`\n${stale} file(s) stale — run: node scripts/build.mjs`);
  if (stale || problems.length) process.exit(1);
  console.log("all SKILL.md files current, manifests consistent");
} else {
  console.log(written ? `\n${written} file(s) written` : "already up to date");
  if (problems.length) process.exit(1);
}
